remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale                   : "en-CA"
title                    : "Nolan Woods"
title_separator          : "-"
name                     : "Nolan Woods"
description              : "Personal blog and home for my various projects."
url                      : https://innovate-invent.com
baseurl                  : /
repository               : innovate-invent/innovate-invent.github.io
#teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
staticman:
  branch                 : "master"
reCaptcha:
  siteKey                : "6LeELlIUAAAAAHPqAiGmlrU_DivmPzoVJDoCO1Bx"
  secret                 : "HZzgjWdOm2LXvAEFXPe/rK5TXJ3pa+E5SMaJ0Lg2ji3HOilw/UjypVMLvvl0v/FFs2g23wIA6uqUAyVaO4v+FH03HyGctWt++dMSpj4GRUR50/UZL4unw0b3zVHKfq9ssqt6EQYJaHK8koBIfd8tUFgR+HNzYz52LZ2UXQw/Mjg="
# atom_feed:
#  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
