remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale                   : "en-CA"
title                    : "Nolan Woods"
title_separator          : "-"
name                     : "Nolan Woods"
description              : "Personal blog and home for my various projects."
url                      : https://innovate-invent.com
baseurl                  : /
repository               : innovate-invent/innovate-invent.github.io
#teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "staticman_v2" "custom"
staticman:
  branch                 : "master"
reCaptcha:
  siteKey                : "6LeELlIUAAAAAHPqAiGmlrU_DivmPzoVJDoCO1Bx"
  secret                 : "HZzgjWdOm2LXvAEFXPe/rK5TXJ3pa+E5SMaJ0Lg2ji3HOilw/UjypVMLvvl0v/FFs2g23wIA6uqUAyVaO4v+FH03HyGctWt++dMSpj4GRUR50/UZL4unw0b3zVHKfq9ssqt6EQYJaHK8koBIfd8tUFgR+HNzYz52LZ2UXQw/Mjg="
# atom_feed:
#  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
# search_provider          : # lunr (default), algolia
# algolia:
#  application_id         : # YOUR_APPLICATION_ID
#  index_name             : # YOUR_INDEX_NAME
#  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
#  powered_by             : # true (default), false

# SEO Related
google_site_verification : "c4JKI7gKnqrxLJeFo7o1NFXOldmR_T77ffgPCJua_tY"
# bing_site_verification   :
# yandex_site_verification :
# naver_site_verification  :

# Social Sharing
# twitter:
#  username               :
# facebook:
#  username               :
#  app_id                 :
#  publisher              :
#og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
#social:
#  type                   : # Person or Organization (defaults to Person)
#  name                   : # If the user or organization name differs from the site's name
#  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-117242191-1"


# Site Author
author:
  name             : "Nolan Woods"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an amazing person."
  location         : "Canada"
  email            : "nolan@i2labs.ca"
  #uri              : "innovate-invent.com"
  home             : # null (default), "absolute or relative url to link to author home"
  #bitbucket        :
  #codepen          :
  #dribbble         :
  #flickr           :
  #facebook         :
  #foursquare       :
  #github           : innovate-invent
  #gitlab           :
  #google_plus      :
  #keybase          :
  #instagram        :
  #lastfm           :
  #linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  #pinterest        :
  #soundcloud       :
  #stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  #steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  #tumblr           :
  #twitter          :
  #vine             :
  #weibo            :
  #xing             :
  #youtube          : # "https://youtube.com/c/MichaelRoseDesign"


# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

